"""email reminders

Revision ID: 08c795a58c65
Revises: 3ea6890138b6
Create Date: 2022-07-12 12:07:36.474337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c795a58c65'
down_revision = '3ea6890138b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('email_reminders', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'email_reminders')
    # ### end Alembic commands ###
