"""add back compatability to fish

Revision ID: 0979a17f743f
Revises: 7fdf8593c13d
Create Date: 2022-07-22 16:46:13.277639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0979a17f743f'
down_revision = '7fdf8593c13d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fish', sa.Column('system', sa.String(length=64), nullable=True))
    op.add_column('fish', sa.Column('old_code', sa.String(length=64), nullable=True))
    op.add_column('fish', sa.Column('old_license', sa.String(length=64), nullable=True))
    op.add_column('fish', sa.Column('old_mID', sa.String(length=64), nullable=True))
    op.add_column('fish', sa.Column('old_mStock', sa.String(length=64), nullable=True))
    op.add_column('fish', sa.Column('old_fID', sa.String(length=64), nullable=True))
    op.add_column('fish', sa.Column('old_fStock', sa.String(length=64), nullable=True))
    op.add_column('fish', sa.Column('old_birthday', sa.String(length=64), nullable=True))
    op.add_column('fish', sa.Column('old_arrival', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fish', 'old_arrival')
    op.drop_column('fish', 'old_birthday')
    op.drop_column('fish', 'old_fStock')
    op.drop_column('fish', 'old_fID')
    op.drop_column('fish', 'old_mStock')
    op.drop_column('fish', 'old_mID')
    op.drop_column('fish', 'old_license')
    op.drop_column('fish', 'old_code')
    op.drop_column('fish', 'system')
    # ### end Alembic commands ###
