"""add allele

Revision ID: 0d8eae9d3b09
Revises: 2ba30c8073c9
Create Date: 2022-07-20 09:30:16.058245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d8eae9d3b09'
down_revision = '2ba30c8073c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allele',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fish_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('unidentified', sa.Boolean(), nullable=True),
    sa.Column('identified', sa.Boolean(), nullable=True),
    sa.Column('homozygous', sa.Boolean(), nullable=True),
    sa.Column('heterozygous', sa.Boolean(), nullable=True),
    sa.Column('hemizygous', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fish_id'], ['fish.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_fish_allele', table_name='fish')
    op.drop_column('fish', 'allele')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fish', sa.Column('allele', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_fish_allele', 'fish', ['allele'], unique=False)
    op.drop_table('allele')
    # ### end Alembic commands ###
