"""add change note

Revision ID: 0e50db87947f
Revises: 1ac1404badbb
Create Date: 2022-07-28 10:48:23.582854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e50db87947f'
down_revision = '1ac1404badbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change', 'note')
    # ### end Alembic commands ###
