"""add age reminder

Revision ID: 1420a134ff50
Revises: 37ebee866bcb
Create Date: 2022-07-21 16:14:28.473053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1420a134ff50'
down_revision = '37ebee866bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fish', sa.Column('age_reminder', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fish', 'age_reminder')
    # ### end Alembic commands ###
