"""remove photos

Revision ID: 164a482271b4
Revises: a1dbe7bd41a0
Create Date: 2022-07-21 08:56:05.492567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164a482271b4'
down_revision = 'a1dbe7bd41a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fish', 'photos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fish', sa.Column('photos', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
