"""add origin tank

Revision ID: 1ac1404badbb
Revises: 
Create Date: 2022-07-23 11:04:35.491181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac1404badbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('project_license', sa.String(length=120), nullable=True),
    sa.Column('personal_license', sa.String(length=120), nullable=True),
    sa.Column('personal_document', sa.Boolean(), nullable=True),
    sa.Column('project_document', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('last_notification_read_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_code'), 'user', ['code'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('fish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fish_id', sa.String(length=264), nullable=True),
    sa.Column('tank_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('stock', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('protocol', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('date_of_arrival', sa.Date(), nullable=True),
    sa.Column('months', sa.Integer(), nullable=True),
    sa.Column('age_reminder', sa.String(length=64), nullable=True),
    sa.Column('mutant_gene', sa.Text(), nullable=True),
    sa.Column('transgenes', sa.Text(), nullable=True),
    sa.Column('cross_type', sa.String(length=64), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('added', sa.DateTime(), nullable=True),
    sa.Column('father_id', sa.Integer(), nullable=True),
    sa.Column('mother_id', sa.Integer(), nullable=True),
    sa.Column('project_license_holder_id', sa.Integer(), nullable=True),
    sa.Column('user_code_id', sa.Integer(), nullable=True),
    sa.Column('males', sa.Integer(), nullable=True),
    sa.Column('females', sa.Integer(), nullable=True),
    sa.Column('unsexed', sa.Integer(), nullable=True),
    sa.Column('carriers', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('links', sa.Text(), nullable=True),
    sa.Column('origin_tank_id', sa.Integer(), nullable=True),
    sa.Column('system', sa.String(length=64), nullable=True),
    sa.Column('old_code', sa.String(length=64), nullable=True),
    sa.Column('old_license', sa.String(length=64), nullable=True),
    sa.Column('old_mID', sa.String(length=64), nullable=True),
    sa.Column('old_mStock', sa.String(length=64), nullable=True),
    sa.Column('old_fID', sa.String(length=64), nullable=True),
    sa.Column('old_fStock', sa.String(length=64), nullable=True),
    sa.Column('old_birthday', sa.String(length=64), nullable=True),
    sa.Column('old_arrival', sa.String(length=64), nullable=True),
    sa.Column('old_allele', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['father_id'], ['fish.id'], ),
    sa.ForeignKeyConstraint(['mother_id'], ['fish.id'], ),
    sa.ForeignKeyConstraint(['origin_tank_id'], ['fish.id'], ),
    sa.ForeignKeyConstraint(['project_license_holder_id'], ['user.project_license'], ),
    sa.ForeignKeyConstraint(['user_code_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fish_birthday'), 'fish', ['birthday'], unique=False)
    op.create_index(op.f('ix_fish_date_of_arrival'), 'fish', ['date_of_arrival'], unique=False)
    op.create_index(op.f('ix_fish_fish_id'), 'fish', ['fish_id'], unique=False)
    op.create_index(op.f('ix_fish_protocol'), 'fish', ['protocol'], unique=False)
    op.create_index(op.f('ix_fish_status'), 'fish', ['status'], unique=False)
    op.create_index(op.f('ix_fish_stock'), 'fish', ['stock'], unique=False)
    op.create_index(op.f('ix_fish_tank_id'), 'fish', ['tank_id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('emails', sa.Boolean(), nullable=True),
    sa.Column('email_reminders', sa.Boolean(), nullable=True),
    sa.Column('add_notifications', sa.Boolean(), nullable=True),
    sa.Column('change_notifications', sa.Boolean(), nullable=True),
    sa.Column('custom_reminder', sa.Boolean(), nullable=True),
    sa.Column('age_notifications', sa.Boolean(), nullable=True),
    sa.Column('pl_add_notifications', sa.Boolean(), nullable=True),
    sa.Column('pl_custom_reminder', sa.Boolean(), nullable=True),
    sa.Column('pl_age_notifications', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allele',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fish_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('unidentified', sa.Boolean(), nullable=True),
    sa.Column('identified', sa.Boolean(), nullable=True),
    sa.Column('homozygous', sa.Boolean(), nullable=True),
    sa.Column('heterozygous', sa.Boolean(), nullable=True),
    sa.Column('hemizygous', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fish_id'], ['fish.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fish_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('contents', sa.String(length=64), nullable=True),
    sa.Column('change_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fish_id'], ['fish.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fish_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['fish_id'], ['fish.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fish_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('message', sa.String(length=64), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fish_id'], ['fish.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fish_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('contents', sa.String(length=64), nullable=True),
    sa.Column('field', sa.String(length=64), nullable=True),
    sa.Column('old', sa.String(length=64), nullable=True),
    sa.Column('new', sa.String(length=64), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('notification_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fish_id'], ['fish.id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('change')
    op.drop_table('reminder')
    op.drop_table('photo')
    op.drop_table('notification')
    op.drop_table('allele')
    op.drop_table('settings')
    op.drop_index(op.f('ix_fish_tank_id'), table_name='fish')
    op.drop_index(op.f('ix_fish_stock'), table_name='fish')
    op.drop_index(op.f('ix_fish_status'), table_name='fish')
    op.drop_index(op.f('ix_fish_protocol'), table_name='fish')
    op.drop_index(op.f('ix_fish_fish_id'), table_name='fish')
    op.drop_index(op.f('ix_fish_date_of_arrival'), table_name='fish')
    op.drop_index(op.f('ix_fish_birthday'), table_name='fish')
    op.drop_table('fish')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_code'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
