"""add old stock

Revision ID: 21bbc4d41c3d
Revises: a72d8d23705e
Create Date: 2022-07-31 11:41:38.356516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21bbc4d41c3d'
down_revision = 'a72d8d23705e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fish', sa.Column('old_stock', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fish', 'old_stock')
    # ### end Alembic commands ###
