"""add stock alive check

Revision ID: 2b9d37790b98
Revises: 1c3bb52048ba
Create Date: 2022-07-31 11:55:47.654564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b9d37790b98'
down_revision = '1c3bb52048ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('fish_alive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'fish_alive')
    # ### end Alembic commands ###
