"""make photos int

Revision ID: 33baf92cc43f
Revises: 9d70e5ab8ea0
Create Date: 2022-07-20 15:59:50.370521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33baf92cc43f'
down_revision = '9d70e5ab8ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fish', sa.Column('num_of_photos', sa.Integer(), nullable=True))
    op.drop_column('fish', 'photo_links')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fish', sa.Column('photo_links', sa.TEXT(), nullable=True))
    op.drop_column('fish', 'num_of_photos')
    # ### end Alembic commands ###
