"""add personal License files

Revision ID: 37ebee866bcb
Revises: 7b3af6b607c8
Create Date: 2022-07-21 13:32:13.268945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ebee866bcb'
down_revision = '7b3af6b607c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('personal_document', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('project_document', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'project_document')
    op.drop_column('user', 'personal_document')
    # ### end Alembic commands ###
