"""add intial fish

Revision ID: 43274f831d18
Revises: bd07d0a05f3e
Create Date: 2022-06-17 10:40:02.202254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43274f831d18'
down_revision = 'bd07d0a05f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fish_id', sa.String(length=64), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('date_of_arrival', sa.DateTime(), nullable=True),
    sa.Column('stock', sa.String(length=64), nullable=True),
    sa.Column('project_license', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('allele', sa.String(length=64), nullable=True),
    sa.Column('mutant_gene', sa.String(length=64), nullable=True),
    sa.Column('transgenes', sa.String(length=64), nullable=True),
    sa.Column('protocol', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fish_allele'), 'fish', ['allele'], unique=False)
    op.create_index(op.f('ix_fish_birthday'), 'fish', ['birthday'], unique=False)
    op.create_index(op.f('ix_fish_date_of_arrival'), 'fish', ['date_of_arrival'], unique=False)
    op.create_index(op.f('ix_fish_fish_id'), 'fish', ['fish_id'], unique=True)
    op.create_index(op.f('ix_fish_mutant_gene'), 'fish', ['mutant_gene'], unique=False)
    op.create_index(op.f('ix_fish_project_license'), 'fish', ['project_license'], unique=False)
    op.create_index(op.f('ix_fish_protocol'), 'fish', ['protocol'], unique=False)
    op.create_index(op.f('ix_fish_status'), 'fish', ['status'], unique=False)
    op.create_index(op.f('ix_fish_stock'), 'fish', ['stock'], unique=False)
    op.create_index(op.f('ix_fish_transgenes'), 'fish', ['transgenes'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fish_transgenes'), table_name='fish')
    op.drop_index(op.f('ix_fish_stock'), table_name='fish')
    op.drop_index(op.f('ix_fish_status'), table_name='fish')
    op.drop_index(op.f('ix_fish_protocol'), table_name='fish')
    op.drop_index(op.f('ix_fish_project_license'), table_name='fish')
    op.drop_index(op.f('ix_fish_mutant_gene'), table_name='fish')
    op.drop_index(op.f('ix_fish_fish_id'), table_name='fish')
    op.drop_index(op.f('ix_fish_date_of_arrival'), table_name='fish')
    op.drop_index(op.f('ix_fish_birthday'), table_name='fish')
    op.drop_index(op.f('ix_fish_allele'), table_name='fish')
    op.drop_table('fish')
    # ### end Alembic commands ###
