"""more settings

Revision ID: 4942aa5600e1
Revises: 56f5657e3287
Create Date: 2022-07-11 10:15:08.031902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4942aa5600e1'
down_revision = '56f5657e3287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('add_notifications', sa.Boolean(), nullable=True))
    op.add_column('settings', sa.Column('change_notifications', sa.Boolean(), nullable=True))
    op.add_column('settings', sa.Column('turnover_notifications', sa.Boolean(), nullable=True))
    op.add_column('settings', sa.Column('age_notifications', sa.Boolean(), nullable=True))
    op.add_column('settings', sa.Column('pl_add_notifications', sa.Boolean(), nullable=True))
    op.add_column('settings', sa.Column('pl_change_notifications', sa.Boolean(), nullable=True))
    op.add_column('settings', sa.Column('pl_turnover_notifications', sa.Boolean(), nullable=True))
    op.add_column('settings', sa.Column('pl_age_notifications', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'pl_age_notifications')
    op.drop_column('settings', 'pl_turnover_notifications')
    op.drop_column('settings', 'pl_change_notifications')
    op.drop_column('settings', 'pl_add_notifications')
    op.drop_column('settings', 'age_notifications')
    op.drop_column('settings', 'turnover_notifications')
    op.drop_column('settings', 'change_notifications')
    op.drop_column('settings', 'add_notifications')
    # ### end Alembic commands ###
