"""change settings

Revision ID: 5cc27c51c388
Revises: 4942aa5600e1
Create Date: 2022-07-11 10:47:21.419676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cc27c51c388'
down_revision = '4942aa5600e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'pl_change_notifications')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('pl_change_notifications', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
