"""make settings one to one

Revision ID: 632c1279fafd
Revises: d3a184dc7e0c
Create Date: 2022-06-20 10:40:54.432032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632c1279fafd'
down_revision = 'd3a184dc7e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('emails', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'emails')
    # ### end Alembic commands ###
