"""remove uniques

Revision ID: 638a5f5df595
Revises: 4e8990660c56
Create Date: 2022-06-25 09:39:07.571000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638a5f5df595'
down_revision = '4e8990660c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fish_fish_id', table_name='fish')
    op.create_index(op.f('ix_fish_fish_id'), 'fish', ['fish_id'], unique=False)
    op.drop_index('ix_fish_tank_id', table_name='fish')
    op.create_index(op.f('ix_fish_tank_id'), 'fish', ['tank_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fish_tank_id'), table_name='fish')
    op.create_index('ix_fish_tank_id', 'fish', ['tank_id'], unique=False)
    op.drop_index(op.f('ix_fish_fish_id'), table_name='fish')
    op.create_index('ix_fish_fish_id', 'fish', ['fish_id'], unique=False)
    # ### end Alembic commands ###
