"""add pl email reminders

Revision ID: 6c8eb144fe05
Revises: 0e50db87947f
Create Date: 2022-07-28 16:01:52.538890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8eb144fe05'
down_revision = '0e50db87947f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('pl_email_reminders', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'pl_email_reminders')
    # ### end Alembic commands ###
