"""add fish alerts

Revision ID: 783ce1bafdce
Revises: 5cc27c51c388
Create Date: 2022-07-11 11:21:11.444909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783ce1bafdce'
down_revision = '5cc27c51c388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fish', sa.Column('alert_date', sa.Date(), nullable=True))
    op.add_column('fish', sa.Column('alert_msg', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_fish_alert_date'), 'fish', ['alert_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fish_alert_date'), table_name='fish')
    op.drop_column('fish', 'alert_msg')
    op.drop_column('fish', 'alert_date')
    # ### end Alembic commands ###
