"""update notification to icon to user

Revision ID: 7ceaf9c653ff
Revises: 4778d57220a0
Create Date: 2022-07-08 09:29:58.168914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ceaf9c653ff'
down_revision = '4778d57220a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fish', 'last_notification_read_time')
    op.add_column('user', sa.Column('last_notification_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_notification_read_time')
    op.add_column('fish', sa.Column('last_notification_read_time', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
