"""change mutant and transgenes

Revision ID: 7fdf8593c13d
Revises: b536077a9543
Create Date: 2022-07-22 09:40:08.128589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fdf8593c13d'
down_revision = 'b536077a9543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fish_cross_type', table_name='fish')
    op.drop_index('ix_fish_mutant_gene', table_name='fish')
    op.drop_index('ix_fish_transgenes', table_name='fish')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_fish_transgenes', 'fish', ['transgenes'], unique=False)
    op.create_index('ix_fish_mutant_gene', 'fish', ['mutant_gene'], unique=False)
    op.create_index('ix_fish_cross_type', 'fish', ['cross_type'], unique=False)
    # ### end Alembic commands ###
