"""remove username

Revision ID: 85234621091b
Revises: 48f91e32805f
Create Date: 2022-06-06 10:12:50.379722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85234621091b'
down_revision = '48f91e32805f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_username', table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    # ### end Alembic commands ###
