"""add User Last Seen

Revision ID: 900708145e50
Revises: 82c53a5207ef
Create Date: 2022-06-06 09:43:42.321948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900708145e50'
down_revision = '82c53a5207ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###
