"""add field to changes

Revision ID: 961ca1bb4a4d
Revises: d36bebb1fe0c
Create Date: 2022-06-27 22:32:58.663755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '961ca1bb4a4d'
down_revision = 'd36bebb1fe0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change', sa.Column('field', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change', 'field')
    # ### end Alembic commands ###
