"""update transgene

Revision ID: 96cfb645dd14
Revises: bd4c3aee1dd3
Create Date: 2022-08-05 13:16:16.561163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96cfb645dd14'
down_revision = 'bd4c3aee1dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fish', sa.Column('old_transgenes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fish', 'old_transgenes')
    # ### end Alembic commands ###
