"""remove turnover reminder

Revision ID: a004d83099f5
Revises: 1420a134ff50
Create Date: 2022-07-21 16:29:53.814618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a004d83099f5'
down_revision = '1420a134ff50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'pl_turnover_notifications')
    op.drop_column('settings', 'turnover_notifications')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('turnover_notifications', sa.BOOLEAN(), nullable=True))
    op.add_column('settings', sa.Column('pl_turnover_notifications', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
