"""add fish months

Revision ID: b536077a9543
Revises: 8d6931abedb0
Create Date: 2022-07-21 19:16:09.224124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b536077a9543'
down_revision = '8d6931abedb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fish', sa.Column('months', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fish', 'months')
    # ### end Alembic commands ###
