"""remove transgenes text

Revision ID: bd4c3aee1dd3
Revises: b097367ca68d
Create Date: 2022-08-05 12:53:36.633212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd4c3aee1dd3'
down_revision = 'b097367ca68d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fish', 'transgenes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fish', sa.Column('transgenes', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
