"""add stock culled count

Revision ID: cacded29a323
Revises: 2b9d37790b98
Create Date: 2022-08-05 10:47:12.195296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cacded29a323'
down_revision = '2b9d37790b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('culled', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'culled')
    # ### end Alembic commands ###
