"""photos and links

Revision ID: f9729c99bef7
Revises: 0d8eae9d3b09
Create Date: 2022-07-20 15:20:15.638431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9729c99bef7'
down_revision = '0d8eae9d3b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fish', sa.Column('photo_links', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fish', 'photo_links')
    # ### end Alembic commands ###
